### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Shashwat4824G** [NozzOne/topgg-voter#2]
hey bro, Is it safe for karuta? also, how to setup?

**Comment by valentin-marquez** [comment]
I would say that it is safe for all bots, since it does not interact directly with them, but with the top.gg page that I guess I did there goes the question, I would say that it is 90% safe, the program uses selenium to automate google chrome. so the vote made by the program simulates a real one.

On the other hand you can see how to configure the program [HERE](https://github.com/NozzOne/topgg-voter/blob/main/readme.md)
